/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app-common/zap-generated/cluster-objects.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/Decode.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/util/basic-types.h>

namespace chip {
namespace app {
namespace clusters {

// AccountLogin Cluster Commands
namespace AccountLogin {

namespace GetSetupPINCommandParams {
enum FieldId
{
    kTempAccountIdentifierFieldId = 0,
};

struct Type
{
public:
    Span<const char> tempAccountIdentifier;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetSetupPINCommandParams
namespace LoginCommandParams {
enum FieldId
{
    kTempAccountIdentifierFieldId = 0,
    kSetupPINFieldId              = 1,
};

struct Type
{
public:
    Span<const char> tempAccountIdentifier;
    Span<const char> setupPIN;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LoginCommandParams

namespace GetSetupPINResponseCommandParams {
enum FieldId
{
    kSetupPINFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetSetupPINResponseCommandParams

} // namespace AccountLogin

// AdministratorCommissioning Cluster Commands
namespace AdministratorCommissioning {

namespace OpenBasicCommissioningWindowCommandParams {
enum FieldId
{
    kCommissioningTimeoutFieldId = 0,
};

struct Type
{
public:
    uint16_t commissioningTimeout;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OpenBasicCommissioningWindowCommandParams
namespace OpenCommissioningWindowCommandParams {
enum FieldId
{
    kCommissioningTimeoutFieldId = 0,
    kPAKEVerifierFieldId         = 1,
    kDiscriminatorFieldId        = 2,
    kIterationsFieldId           = 3,
    kSaltFieldId                 = 4,
    kPasscodeIDFieldId           = 5,
};

struct Type
{
public:
    uint16_t commissioningTimeout;
    chip::ByteSpan pAKEVerifier;
    uint16_t discriminator;
    uint32_t iterations;
    chip::ByteSpan salt;
    uint16_t passcodeID;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OpenCommissioningWindowCommandParams
namespace RevokeCommissioningCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RevokeCommissioningCommandParams

} // namespace AdministratorCommissioning

// ApplicationBasic Cluster Commands
namespace ApplicationBasic {

namespace ChangeStatusCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    ApplicationBasicStatus status;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ChangeStatusCommandParams

} // namespace ApplicationBasic

// ApplicationLauncher Cluster Commands
namespace ApplicationLauncher {

namespace LaunchAppCommandParams {
enum FieldId
{
    kDataFieldId            = 0,
    kCatalogVendorIdFieldId = 1,
    kApplicationIdFieldId   = 2,
};

struct Type
{
public:
    Span<const char> data;
    uint16_t catalogVendorId;
    Span<const char> applicationId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LaunchAppCommandParams

namespace LaunchAppResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
    kDataFieldId   = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LaunchAppResponseCommandParams

} // namespace ApplicationLauncher

// AudioOutput Cluster Commands
namespace AudioOutput {

namespace RenameOutputCommandParams {
enum FieldId
{
    kIndexFieldId = 0,
    kNameFieldId  = 1,
};

struct Type
{
public:
    uint8_t index;
    Span<const char> name;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RenameOutputCommandParams
namespace SelectOutputCommandParams {
enum FieldId
{
    kIndexFieldId = 0,
};

struct Type
{
public:
    uint8_t index;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SelectOutputCommandParams

} // namespace AudioOutput

// BarrierControl Cluster Commands
namespace BarrierControl {

namespace BarrierControlGoToPercentCommandParams {
enum FieldId
{
    kPercentOpenFieldId = 0,
};

struct Type
{
public:
    uint8_t percentOpen;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace BarrierControlGoToPercentCommandParams
namespace BarrierControlStopCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace BarrierControlStopCommandParams

} // namespace BarrierControl

// Basic Cluster Commands
namespace Basic {

namespace MfgSpecificPingCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MfgSpecificPingCommandParams

} // namespace Basic

// BinaryInputBasic Cluster Commands
namespace BinaryInputBasic {

} // namespace BinaryInputBasic

// Binding Cluster Commands
namespace Binding {

namespace BindCommandParams {
enum FieldId
{
    kNodeIdFieldId     = 0,
    kGroupIdFieldId    = 1,
    kEndpointIdFieldId = 2,
    kClusterIdFieldId  = 3,
};

struct Type
{
public:
    uint64_t nodeId;
    uint16_t groupId;
    uint16_t endpointId;
    uint32_t clusterId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace BindCommandParams
namespace UnbindCommandParams {
enum FieldId
{
    kNodeIdFieldId     = 0,
    kGroupIdFieldId    = 1,
    kEndpointIdFieldId = 2,
    kClusterIdFieldId  = 3,
};

struct Type
{
public:
    uint64_t nodeId;
    uint16_t groupId;
    uint16_t endpointId;
    uint32_t clusterId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UnbindCommandParams

} // namespace Binding

// BridgedDeviceBasic Cluster Commands
namespace BridgedDeviceBasic {

} // namespace BridgedDeviceBasic

// ColorControl Cluster Commands
namespace ColorControl {

namespace ColorLoopSetCommandParams {
enum FieldId
{
    kUpdateFlagsFieldId     = 0,
    kActionFieldId          = 1,
    kDirectionFieldId       = 2,
    kTimeFieldId            = 3,
    kStartHueFieldId        = 4,
    kOptionsMaskFieldId     = 5,
    kOptionsOverrideFieldId = 6,
};

struct Type
{
public:
    uint8_t updateFlags;
    ColorLoopAction action;
    ColorLoopDirection direction;
    uint16_t time;
    uint16_t startHue;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ColorLoopSetCommandParams
namespace EnhancedMoveHueCommandParams {
enum FieldId
{
    kMoveModeFieldId        = 0,
    kRateFieldId            = 1,
    kOptionsMaskFieldId     = 2,
    kOptionsOverrideFieldId = 3,
};

struct Type
{
public:
    HueMoveMode moveMode;
    uint16_t rate;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnhancedMoveHueCommandParams
namespace EnhancedMoveToHueCommandParams {
enum FieldId
{
    kEnhancedHueFieldId     = 0,
    kDirectionFieldId       = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    uint16_t enhancedHue;
    HueDirection direction;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnhancedMoveToHueCommandParams
namespace EnhancedMoveToHueAndSaturationCommandParams {
enum FieldId
{
    kEnhancedHueFieldId     = 0,
    kSaturationFieldId      = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    uint16_t enhancedHue;
    uint8_t saturation;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnhancedMoveToHueAndSaturationCommandParams
namespace EnhancedStepHueCommandParams {
enum FieldId
{
    kStepModeFieldId        = 0,
    kStepSizeFieldId        = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    HueStepMode stepMode;
    uint16_t stepSize;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnhancedStepHueCommandParams
namespace MoveColorCommandParams {
enum FieldId
{
    kRateXFieldId           = 0,
    kRateYFieldId           = 1,
    kOptionsMaskFieldId     = 2,
    kOptionsOverrideFieldId = 3,
};

struct Type
{
public:
    int16_t rateX;
    int16_t rateY;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveColorCommandParams
namespace MoveColorTemperatureCommandParams {
enum FieldId
{
    kMoveModeFieldId                = 0,
    kRateFieldId                    = 1,
    kColorTemperatureMinimumFieldId = 2,
    kColorTemperatureMaximumFieldId = 3,
    kOptionsMaskFieldId             = 4,
    kOptionsOverrideFieldId         = 5,
};

struct Type
{
public:
    HueMoveMode moveMode;
    uint16_t rate;
    uint16_t colorTemperatureMinimum;
    uint16_t colorTemperatureMaximum;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveColorTemperatureCommandParams
namespace MoveHueCommandParams {
enum FieldId
{
    kMoveModeFieldId        = 0,
    kRateFieldId            = 1,
    kOptionsMaskFieldId     = 2,
    kOptionsOverrideFieldId = 3,
};

struct Type
{
public:
    HueMoveMode moveMode;
    uint8_t rate;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveHueCommandParams
namespace MoveSaturationCommandParams {
enum FieldId
{
    kMoveModeFieldId        = 0,
    kRateFieldId            = 1,
    kOptionsMaskFieldId     = 2,
    kOptionsOverrideFieldId = 3,
};

struct Type
{
public:
    SaturationMoveMode moveMode;
    uint8_t rate;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveSaturationCommandParams
namespace MoveToColorCommandParams {
enum FieldId
{
    kColorXFieldId          = 0,
    kColorYFieldId          = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    uint16_t colorX;
    uint16_t colorY;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToColorCommandParams
namespace MoveToColorTemperatureCommandParams {
enum FieldId
{
    kColorTemperatureFieldId = 0,
    kTransitionTimeFieldId   = 1,
    kOptionsMaskFieldId      = 2,
    kOptionsOverrideFieldId  = 3,
};

struct Type
{
public:
    uint16_t colorTemperature;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToColorTemperatureCommandParams
namespace MoveToHueCommandParams {
enum FieldId
{
    kHueFieldId             = 0,
    kDirectionFieldId       = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    uint8_t hue;
    HueDirection direction;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToHueCommandParams
namespace MoveToHueAndSaturationCommandParams {
enum FieldId
{
    kHueFieldId             = 0,
    kSaturationFieldId      = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    uint8_t hue;
    uint8_t saturation;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToHueAndSaturationCommandParams
namespace MoveToSaturationCommandParams {
enum FieldId
{
    kSaturationFieldId      = 0,
    kTransitionTimeFieldId  = 1,
    kOptionsMaskFieldId     = 2,
    kOptionsOverrideFieldId = 3,
};

struct Type
{
public:
    uint8_t saturation;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToSaturationCommandParams
namespace StepColorCommandParams {
enum FieldId
{
    kStepXFieldId           = 0,
    kStepYFieldId           = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    int16_t stepX;
    int16_t stepY;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepColorCommandParams
namespace StepColorTemperatureCommandParams {
enum FieldId
{
    kStepModeFieldId                = 0,
    kStepSizeFieldId                = 1,
    kTransitionTimeFieldId          = 2,
    kColorTemperatureMinimumFieldId = 3,
    kColorTemperatureMaximumFieldId = 4,
    kOptionsMaskFieldId             = 5,
    kOptionsOverrideFieldId         = 6,
};

struct Type
{
public:
    HueStepMode stepMode;
    uint16_t stepSize;
    uint16_t transitionTime;
    uint16_t colorTemperatureMinimum;
    uint16_t colorTemperatureMaximum;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepColorTemperatureCommandParams
namespace StepHueCommandParams {
enum FieldId
{
    kStepModeFieldId        = 0,
    kStepSizeFieldId        = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    HueStepMode stepMode;
    uint8_t stepSize;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepHueCommandParams
namespace StepSaturationCommandParams {
enum FieldId
{
    kStepModeFieldId        = 0,
    kStepSizeFieldId        = 1,
    kTransitionTimeFieldId  = 2,
    kOptionsMaskFieldId     = 3,
    kOptionsOverrideFieldId = 4,
};

struct Type
{
public:
    SaturationStepMode stepMode;
    uint8_t stepSize;
    uint16_t transitionTime;
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepSaturationCommandParams
namespace StopMoveStepCommandParams {
enum FieldId
{
    kOptionsMaskFieldId     = 0,
    kOptionsOverrideFieldId = 1,
};

struct Type
{
public:
    uint8_t optionsMask;
    uint8_t optionsOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StopMoveStepCommandParams

} // namespace ColorControl

// ContentLauncher Cluster Commands
namespace ContentLauncher {

namespace LaunchContentCommandParams {
enum FieldId
{
    kAutoPlayFieldId = 0,
    kDataFieldId     = 1,
};

struct Type
{
public:
    bool autoPlay;
    Span<const char> data;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LaunchContentCommandParams
namespace LaunchURLCommandParams {
enum FieldId
{
    kContentURLFieldId    = 0,
    kDisplayStringFieldId = 1,
};

struct Type
{
public:
    Span<const char> contentURL;
    Span<const char> displayString;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LaunchURLCommandParams

namespace LaunchContentResponseCommandParams {
enum FieldId
{
    kDataFieldId                = 0,
    kContentLaunchStatusFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LaunchContentResponseCommandParams
namespace LaunchURLResponseCommandParams {
enum FieldId
{
    kDataFieldId                = 0,
    kContentLaunchStatusFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LaunchURLResponseCommandParams

} // namespace ContentLauncher

// Descriptor Cluster Commands
namespace Descriptor {

} // namespace Descriptor

// DiagnosticLogs Cluster Commands
namespace DiagnosticLogs {

namespace RetrieveLogsRequestCommandParams {
enum FieldId
{
    kIntentFieldId                 = 0,
    kRequestedProtocolFieldId      = 1,
    kTransferFileDesignatorFieldId = 2,
};

struct Type
{
public:
    LogsIntent intent;
    LogsTransferProtocol requestedProtocol;
    chip::ByteSpan transferFileDesignator;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RetrieveLogsRequestCommandParams

} // namespace DiagnosticLogs

// DoorLock Cluster Commands
namespace DoorLock {

namespace ClearAllPinsCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearAllPinsCommandParams
namespace ClearAllRfidsCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearAllRfidsCommandParams
namespace ClearHolidayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId = 0,
};

struct Type
{
public:
    uint8_t scheduleId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearHolidayScheduleCommandParams
namespace ClearPinCommandParams {
enum FieldId
{
    kUserIdFieldId = 0,
};

struct Type
{
public:
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearPinCommandParams
namespace ClearRfidCommandParams {
enum FieldId
{
    kUserIdFieldId = 0,
};

struct Type
{
public:
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearRfidCommandParams
namespace ClearWeekdayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId = 0,
    kUserIdFieldId     = 1,
};

struct Type
{
public:
    uint8_t scheduleId;
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearWeekdayScheduleCommandParams
namespace ClearYeardayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId = 0,
    kUserIdFieldId     = 1,
};

struct Type
{
public:
    uint8_t scheduleId;
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearYeardayScheduleCommandParams
namespace GetHolidayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId = 0,
};

struct Type
{
public:
    uint8_t scheduleId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetHolidayScheduleCommandParams
namespace GetLogRecordCommandParams {
enum FieldId
{
    kLogIndexFieldId = 0,
};

struct Type
{
public:
    uint16_t logIndex;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetLogRecordCommandParams
namespace GetPinCommandParams {
enum FieldId
{
    kUserIdFieldId = 0,
};

struct Type
{
public:
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetPinCommandParams
namespace GetRfidCommandParams {
enum FieldId
{
    kUserIdFieldId = 0,
};

struct Type
{
public:
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetRfidCommandParams
namespace GetUserTypeCommandParams {
enum FieldId
{
    kUserIdFieldId = 0,
};

struct Type
{
public:
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetUserTypeCommandParams
namespace GetWeekdayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId = 0,
    kUserIdFieldId     = 1,
};

struct Type
{
public:
    uint8_t scheduleId;
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetWeekdayScheduleCommandParams
namespace GetYeardayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId = 0,
    kUserIdFieldId     = 1,
};

struct Type
{
public:
    uint8_t scheduleId;
    uint16_t userId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetYeardayScheduleCommandParams
namespace LockDoorCommandParams {
enum FieldId
{
    kPinFieldId = 0,
};

struct Type
{
public:
    Span<const char> pin;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LockDoorCommandParams
namespace SetHolidayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId                 = 0,
    kLocalStartTimeFieldId             = 1,
    kLocalEndTimeFieldId               = 2,
    kOperatingModeDuringHolidayFieldId = 3,
};

struct Type
{
public:
    uint8_t scheduleId;
    uint32_t localStartTime;
    uint32_t localEndTime;
    uint8_t operatingModeDuringHoliday;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetHolidayScheduleCommandParams
namespace SetPinCommandParams {
enum FieldId
{
    kUserIdFieldId     = 0,
    kUserStatusFieldId = 1,
    kUserTypeFieldId   = 2,
    kPinFieldId        = 3,
};

struct Type
{
public:
    uint16_t userId;
    DoorLockUserStatus userStatus;
    DoorLockUserType userType;
    Span<const char> pin;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetPinCommandParams
namespace SetRfidCommandParams {
enum FieldId
{
    kUserIdFieldId     = 0,
    kUserStatusFieldId = 1,
    kUserTypeFieldId   = 2,
    kIdFieldId         = 3,
};

struct Type
{
public:
    uint16_t userId;
    DoorLockUserStatus userStatus;
    DoorLockUserType userType;
    Span<const char> id;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetRfidCommandParams
namespace SetUserTypeCommandParams {
enum FieldId
{
    kUserIdFieldId   = 0,
    kUserTypeFieldId = 1,
};

struct Type
{
public:
    uint16_t userId;
    DoorLockUserType userType;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetUserTypeCommandParams
namespace SetWeekdayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId  = 0,
    kUserIdFieldId      = 1,
    kDaysMaskFieldId    = 2,
    kStartHourFieldId   = 3,
    kStartMinuteFieldId = 4,
    kEndHourFieldId     = 5,
    kEndMinuteFieldId   = 6,
};

struct Type
{
public:
    uint8_t scheduleId;
    uint16_t userId;
    uint8_t daysMask;
    uint8_t startHour;
    uint8_t startMinute;
    uint8_t endHour;
    uint8_t endMinute;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetWeekdayScheduleCommandParams
namespace SetYeardayScheduleCommandParams {
enum FieldId
{
    kScheduleIdFieldId     = 0,
    kUserIdFieldId         = 1,
    kLocalStartTimeFieldId = 2,
    kLocalEndTimeFieldId   = 3,
};

struct Type
{
public:
    uint8_t scheduleId;
    uint16_t userId;
    uint32_t localStartTime;
    uint32_t localEndTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetYeardayScheduleCommandParams
namespace UnlockDoorCommandParams {
enum FieldId
{
    kPinFieldId = 0,
};

struct Type
{
public:
    Span<const char> pin;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UnlockDoorCommandParams
namespace UnlockWithTimeoutCommandParams {
enum FieldId
{
    kTimeoutInSecondsFieldId = 0,
    kPinFieldId              = 1,
};

struct Type
{
public:
    uint16_t timeoutInSeconds;
    Span<const char> pin;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UnlockWithTimeoutCommandParams

namespace ClearAllPinsResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearAllPinsResponseCommandParams
namespace ClearAllRfidsResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearAllRfidsResponseCommandParams
namespace ClearHolidayScheduleResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearHolidayScheduleResponseCommandParams
namespace ClearPinResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearPinResponseCommandParams
namespace ClearRfidResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearRfidResponseCommandParams
namespace ClearWeekdayScheduleResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearWeekdayScheduleResponseCommandParams
namespace ClearYeardayScheduleResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearYeardayScheduleResponseCommandParams
namespace GetHolidayScheduleResponseCommandParams {
enum FieldId
{
    kScheduleIdFieldId                 = 0,
    kStatusFieldId                     = 1,
    kLocalStartTimeFieldId             = 2,
    kLocalEndTimeFieldId               = 3,
    kOperatingModeDuringHolidayFieldId = 4,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetHolidayScheduleResponseCommandParams
namespace GetLogRecordResponseCommandParams {
enum FieldId
{
    kLogEntryIdFieldId         = 0,
    kTimestampFieldId          = 1,
    kEventTypeFieldId          = 2,
    kSourceFieldId             = 3,
    kEventIdOrAlarmCodeFieldId = 4,
    kUserIdFieldId             = 5,
    kPinFieldId                = 6,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetLogRecordResponseCommandParams
namespace GetPinResponseCommandParams {
enum FieldId
{
    kUserIdFieldId     = 0,
    kUserStatusFieldId = 1,
    kUserTypeFieldId   = 2,
    kPinFieldId        = 3,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetPinResponseCommandParams
namespace GetRfidResponseCommandParams {
enum FieldId
{
    kUserIdFieldId     = 0,
    kUserStatusFieldId = 1,
    kUserTypeFieldId   = 2,
    kRfidFieldId       = 3,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetRfidResponseCommandParams
namespace GetUserTypeResponseCommandParams {
enum FieldId
{
    kUserIdFieldId   = 0,
    kUserTypeFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetUserTypeResponseCommandParams
namespace GetWeekdayScheduleResponseCommandParams {
enum FieldId
{
    kScheduleIdFieldId  = 0,
    kUserIdFieldId      = 1,
    kStatusFieldId      = 2,
    kDaysMaskFieldId    = 3,
    kStartHourFieldId   = 4,
    kStartMinuteFieldId = 5,
    kEndHourFieldId     = 6,
    kEndMinuteFieldId   = 7,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetWeekdayScheduleResponseCommandParams
namespace GetYeardayScheduleResponseCommandParams {
enum FieldId
{
    kScheduleIdFieldId     = 0,
    kUserIdFieldId         = 1,
    kStatusFieldId         = 2,
    kLocalStartTimeFieldId = 3,
    kLocalEndTimeFieldId   = 4,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetYeardayScheduleResponseCommandParams
namespace LockDoorResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace LockDoorResponseCommandParams
namespace SetHolidayScheduleResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetHolidayScheduleResponseCommandParams
namespace SetPinResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetPinResponseCommandParams
namespace SetRfidResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetRfidResponseCommandParams
namespace SetUserTypeResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetUserTypeResponseCommandParams
namespace SetWeekdayScheduleResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetWeekdayScheduleResponseCommandParams
namespace SetYeardayScheduleResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetYeardayScheduleResponseCommandParams
namespace UnlockDoorResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UnlockDoorResponseCommandParams
namespace UnlockWithTimeoutResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UnlockWithTimeoutResponseCommandParams

} // namespace DoorLock

// ElectricalMeasurement Cluster Commands
namespace ElectricalMeasurement {

} // namespace ElectricalMeasurement

// EthernetNetworkDiagnostics Cluster Commands
namespace EthernetNetworkDiagnostics {

namespace ResetCountsCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ResetCountsCommandParams

} // namespace EthernetNetworkDiagnostics

// FixedLabel Cluster Commands
namespace FixedLabel {

} // namespace FixedLabel

// FlowMeasurement Cluster Commands
namespace FlowMeasurement {

} // namespace FlowMeasurement

// GeneralCommissioning Cluster Commands
namespace GeneralCommissioning {

namespace ArmFailSafeCommandParams {
enum FieldId
{
    kExpiryLengthSecondsFieldId = 0,
    kBreadcrumbFieldId          = 1,
    kTimeoutMsFieldId           = 2,
};

struct Type
{
public:
    uint16_t expiryLengthSeconds;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ArmFailSafeCommandParams
namespace CommissioningCompleteCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CommissioningCompleteCommandParams
namespace SetRegulatoryConfigCommandParams {
enum FieldId
{
    kLocationFieldId    = 0,
    kCountryCodeFieldId = 1,
    kBreadcrumbFieldId  = 2,
    kTimeoutMsFieldId   = 3,
};

struct Type
{
public:
    RegulatoryLocationType location;
    Span<const char> countryCode;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetRegulatoryConfigCommandParams

namespace ArmFailSafeResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ArmFailSafeResponseCommandParams
namespace CommissioningCompleteResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CommissioningCompleteResponseCommandParams
namespace SetRegulatoryConfigResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetRegulatoryConfigResponseCommandParams

} // namespace GeneralCommissioning

// GeneralDiagnostics Cluster Commands
namespace GeneralDiagnostics {

} // namespace GeneralDiagnostics

// GroupKeyManagement Cluster Commands
namespace GroupKeyManagement {

} // namespace GroupKeyManagement

// Groups Cluster Commands
namespace Groups {

namespace AddGroupCommandParams {
enum FieldId
{
    kGroupIdFieldId   = 0,
    kGroupNameFieldId = 1,
};

struct Type
{
public:
    uint16_t groupId;
    Span<const char> groupName;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddGroupCommandParams
namespace AddGroupIfIdentifyingCommandParams {
enum FieldId
{
    kGroupIdFieldId   = 0,
    kGroupNameFieldId = 1,
};

struct Type
{
public:
    uint16_t groupId;
    Span<const char> groupName;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddGroupIfIdentifyingCommandParams
namespace GetGroupMembershipCommandParams {
enum FieldId
{
    kGroupCountFieldId = 0,
    kGroupListFieldId  = 1,
};

struct Type
{
public:
    uint8_t groupCount;
    DataModel::List<uint16_t> groupList;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetGroupMembershipCommandParams
namespace RemoveAllGroupsCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveAllGroupsCommandParams
namespace RemoveGroupCommandParams {
enum FieldId
{
    kGroupIdFieldId = 0,
};

struct Type
{
public:
    uint16_t groupId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveGroupCommandParams
namespace ViewGroupCommandParams {
enum FieldId
{
    kGroupIdFieldId = 0,
};

struct Type
{
public:
    uint16_t groupId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ViewGroupCommandParams

namespace AddGroupResponseCommandParams {
enum FieldId
{
    kStatusFieldId  = 0,
    kGroupIdFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddGroupResponseCommandParams
namespace GetGroupMembershipResponseCommandParams {
enum FieldId
{
    kCapacityFieldId   = 0,
    kGroupCountFieldId = 1,
    kGroupListFieldId  = 2,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetGroupMembershipResponseCommandParams
namespace RemoveGroupResponseCommandParams {
enum FieldId
{
    kStatusFieldId  = 0,
    kGroupIdFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveGroupResponseCommandParams
namespace ViewGroupResponseCommandParams {
enum FieldId
{
    kStatusFieldId    = 0,
    kGroupIdFieldId   = 1,
    kGroupNameFieldId = 2,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ViewGroupResponseCommandParams

} // namespace Groups

// Identify Cluster Commands
namespace Identify {

namespace IdentifyCommandParams {
enum FieldId
{
    kIdentifyTimeFieldId = 0,
};

struct Type
{
public:
    uint16_t identifyTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace IdentifyCommandParams
namespace IdentifyQueryCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace IdentifyQueryCommandParams

namespace IdentifyQueryResponseCommandParams {
enum FieldId
{
    kTimeoutFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace IdentifyQueryResponseCommandParams

} // namespace Identify

// KeypadInput Cluster Commands
namespace KeypadInput {

namespace SendKeyCommandParams {
enum FieldId
{
    kKeyCodeFieldId = 0,
};

struct Type
{
public:
    KeypadInputCecKeyCode keyCode;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SendKeyCommandParams

namespace SendKeyResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SendKeyResponseCommandParams

} // namespace KeypadInput

// LevelControl Cluster Commands
namespace LevelControl {

namespace MoveCommandParams {
enum FieldId
{
    kMoveModeFieldId       = 0,
    kRateFieldId           = 1,
    kOptionMaskFieldId     = 2,
    kOptionOverrideFieldId = 3,
};

struct Type
{
public:
    MoveMode moveMode;
    uint8_t rate;
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveCommandParams
namespace MoveToLevelCommandParams {
enum FieldId
{
    kLevelFieldId          = 0,
    kTransitionTimeFieldId = 1,
    kOptionMaskFieldId     = 2,
    kOptionOverrideFieldId = 3,
};

struct Type
{
public:
    uint8_t level;
    uint16_t transitionTime;
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToLevelCommandParams
namespace MoveToLevelWithOnOffCommandParams {
enum FieldId
{
    kLevelFieldId          = 0,
    kTransitionTimeFieldId = 1,
};

struct Type
{
public:
    uint8_t level;
    uint16_t transitionTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToLevelWithOnOffCommandParams
namespace MoveWithOnOffCommandParams {
enum FieldId
{
    kMoveModeFieldId = 0,
    kRateFieldId     = 1,
};

struct Type
{
public:
    MoveMode moveMode;
    uint8_t rate;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveWithOnOffCommandParams
namespace StepCommandParams {
enum FieldId
{
    kStepModeFieldId       = 0,
    kStepSizeFieldId       = 1,
    kTransitionTimeFieldId = 2,
    kOptionMaskFieldId     = 3,
    kOptionOverrideFieldId = 4,
};

struct Type
{
public:
    StepMode stepMode;
    uint8_t stepSize;
    uint16_t transitionTime;
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepCommandParams
namespace StepWithOnOffCommandParams {
enum FieldId
{
    kStepModeFieldId       = 0,
    kStepSizeFieldId       = 1,
    kTransitionTimeFieldId = 2,
};

struct Type
{
public:
    StepMode stepMode;
    uint8_t stepSize;
    uint16_t transitionTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepWithOnOffCommandParams
namespace StopCommandParams {
enum FieldId
{
    kOptionMaskFieldId     = 0,
    kOptionOverrideFieldId = 1,
};

struct Type
{
public:
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StopCommandParams
namespace StopWithOnOffCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StopWithOnOffCommandParams

} // namespace LevelControl

// LowPower Cluster Commands
namespace LowPower {

namespace SleepCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SleepCommandParams

} // namespace LowPower

// MediaInput Cluster Commands
namespace MediaInput {

namespace HideInputStatusCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace HideInputStatusCommandParams
namespace RenameInputCommandParams {
enum FieldId
{
    kIndexFieldId = 0,
    kNameFieldId  = 1,
};

struct Type
{
public:
    uint8_t index;
    Span<const char> name;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RenameInputCommandParams
namespace SelectInputCommandParams {
enum FieldId
{
    kIndexFieldId = 0,
};

struct Type
{
public:
    uint8_t index;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SelectInputCommandParams
namespace ShowInputStatusCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ShowInputStatusCommandParams

} // namespace MediaInput

// MediaPlayback Cluster Commands
namespace MediaPlayback {

namespace MediaFastForwardCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaFastForwardCommandParams
namespace MediaNextCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaNextCommandParams
namespace MediaPauseCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaPauseCommandParams
namespace MediaPlayCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaPlayCommandParams
namespace MediaPreviousCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaPreviousCommandParams
namespace MediaRewindCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaRewindCommandParams
namespace MediaSeekCommandParams {
enum FieldId
{
    kPositionFieldId = 0,
};

struct Type
{
public:
    uint64_t position;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaSeekCommandParams
namespace MediaSkipBackwardCommandParams {
enum FieldId
{
    kDeltaPositionMillisecondsFieldId = 0,
};

struct Type
{
public:
    uint64_t deltaPositionMilliseconds;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaSkipBackwardCommandParams
namespace MediaSkipForwardCommandParams {
enum FieldId
{
    kDeltaPositionMillisecondsFieldId = 0,
};

struct Type
{
public:
    uint64_t deltaPositionMilliseconds;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaSkipForwardCommandParams
namespace MediaStartOverCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaStartOverCommandParams
namespace MediaStopCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaStopCommandParams

namespace MediaFastForwardResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaFastForwardResponseCommandParams
namespace MediaNextResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaNextResponseCommandParams
namespace MediaPauseResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaPauseResponseCommandParams
namespace MediaPlayResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaPlayResponseCommandParams
namespace MediaPreviousResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaPreviousResponseCommandParams
namespace MediaRewindResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaRewindResponseCommandParams
namespace MediaSeekResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaSeekResponseCommandParams
namespace MediaSkipBackwardResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaSkipBackwardResponseCommandParams
namespace MediaSkipForwardResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaSkipForwardResponseCommandParams
namespace MediaStartOverResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaStartOverResponseCommandParams
namespace MediaStopResponseCommandParams {
enum FieldId
{
    kMediaPlaybackStatusFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MediaStopResponseCommandParams

} // namespace MediaPlayback

// NetworkCommissioning Cluster Commands
namespace NetworkCommissioning {

namespace AddThreadNetworkCommandParams {
enum FieldId
{
    kOperationalDatasetFieldId = 0,
    kBreadcrumbFieldId         = 1,
    kTimeoutMsFieldId          = 2,
};

struct Type
{
public:
    chip::ByteSpan operationalDataset;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddThreadNetworkCommandParams
namespace AddWiFiNetworkCommandParams {
enum FieldId
{
    kSsidFieldId        = 0,
    kCredentialsFieldId = 1,
    kBreadcrumbFieldId  = 2,
    kTimeoutMsFieldId   = 3,
};

struct Type
{
public:
    chip::ByteSpan ssid;
    chip::ByteSpan credentials;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddWiFiNetworkCommandParams
namespace DisableNetworkCommandParams {
enum FieldId
{
    kNetworkIDFieldId  = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan networkID;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace DisableNetworkCommandParams
namespace EnableNetworkCommandParams {
enum FieldId
{
    kNetworkIDFieldId  = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan networkID;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnableNetworkCommandParams
namespace GetLastNetworkCommissioningResultCommandParams {
enum FieldId
{
    kTimeoutMsFieldId = 0,
};

struct Type
{
public:
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetLastNetworkCommissioningResultCommandParams
namespace RemoveNetworkCommandParams {
enum FieldId
{
    kNetworkIDFieldId  = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan networkID;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveNetworkCommandParams
namespace ScanNetworksCommandParams {
enum FieldId
{
    kSsidFieldId       = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan ssid;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ScanNetworksCommandParams
namespace UpdateThreadNetworkCommandParams {
enum FieldId
{
    kOperationalDatasetFieldId = 0,
    kBreadcrumbFieldId         = 1,
    kTimeoutMsFieldId          = 2,
};

struct Type
{
public:
    chip::ByteSpan operationalDataset;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateThreadNetworkCommandParams
namespace UpdateWiFiNetworkCommandParams {
enum FieldId
{
    kSsidFieldId        = 0,
    kCredentialsFieldId = 1,
    kBreadcrumbFieldId  = 2,
    kTimeoutMsFieldId   = 3,
};

struct Type
{
public:
    chip::ByteSpan ssid;
    chip::ByteSpan credentials;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateWiFiNetworkCommandParams

namespace AddThreadNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddThreadNetworkResponseCommandParams
namespace AddWiFiNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddWiFiNetworkResponseCommandParams
namespace DisableNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace DisableNetworkResponseCommandParams
namespace EnableNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnableNetworkResponseCommandParams
namespace RemoveNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveNetworkResponseCommandParams
namespace ScanNetworksResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId         = 0,
    kDebugTextFieldId         = 1,
    kWifiScanResultsFieldId   = 2,
    kThreadScanResultsFieldId = 3,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ScanNetworksResponseCommandParams
namespace UpdateThreadNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateThreadNetworkResponseCommandParams
namespace UpdateWiFiNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateWiFiNetworkResponseCommandParams

} // namespace NetworkCommissioning

// OtaSoftwareUpdateProvider Cluster Commands
namespace OtaSoftwareUpdateProvider {

namespace ApplyUpdateRequestCommandParams {
enum FieldId
{
    kUpdateTokenFieldId = 0,
    kNewVersionFieldId  = 1,
};

struct Type
{
public:
    chip::ByteSpan updateToken;
    uint32_t newVersion;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ApplyUpdateRequestCommandParams
namespace NotifyUpdateAppliedCommandParams {
enum FieldId
{
    kUpdateTokenFieldId    = 0,
    kCurrentVersionFieldId = 1,
};

struct Type
{
public:
    chip::ByteSpan updateToken;
    uint32_t currentVersion;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace NotifyUpdateAppliedCommandParams
namespace QueryImageCommandParams {
enum FieldId
{
    kVendorIdFieldId            = 0,
    kProductIdFieldId           = 1,
    kImageTypeFieldId           = 2,
    kHardwareVersionFieldId     = 3,
    kCurrentVersionFieldId      = 4,
    kProtocolsSupportedFieldId  = 5,
    kLocationFieldId            = 6,
    kRequestorCanConsentFieldId = 7,
    kMetadataForProviderFieldId = 8,
};

struct Type
{
public:
    uint16_t vendorId;
    uint16_t productId;
    uint16_t imageType;
    uint16_t hardwareVersion;
    uint32_t currentVersion;
    OTADownloadProtocol protocolsSupported;
    Span<const char> location;
    bool requestorCanConsent;
    chip::ByteSpan metadataForProvider;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace QueryImageCommandParams

namespace ApplyUpdateRequestResponseCommandParams {
enum FieldId
{
    kActionFieldId            = 0,
    kDelayedActionTimeFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ApplyUpdateRequestResponseCommandParams
namespace QueryImageResponseCommandParams {
enum FieldId
{
    kStatusFieldId               = 0,
    kDelayedActionTimeFieldId    = 1,
    kImageURIFieldId             = 2,
    kSoftwareVersionFieldId      = 3,
    kUpdateTokenFieldId          = 4,
    kUserConsentNeededFieldId    = 5,
    kMetadataForRequestorFieldId = 6,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace QueryImageResponseCommandParams

} // namespace OtaSoftwareUpdateProvider

// OtaSoftwareUpdateRequestor Cluster Commands
namespace OtaSoftwareUpdateRequestor {

namespace AnnounceOtaProviderCommandParams {
enum FieldId
{
    kServerLocationFieldId     = 0,
    kVendorIdFieldId           = 1,
    kAnnouncementReasonFieldId = 2,
    kMetadataForNodeFieldId    = 3,
};

struct Type
{
public:
    chip::ByteSpan serverLocation;
    uint16_t vendorId;
    OTAAnnouncementReason announcementReason;
    chip::ByteSpan metadataForNode;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AnnounceOtaProviderCommandParams

} // namespace OtaSoftwareUpdateRequestor

// OccupancySensing Cluster Commands
namespace OccupancySensing {

} // namespace OccupancySensing

// OnOff Cluster Commands
namespace OnOff {

namespace OffCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OffCommandParams
namespace OffWithEffectCommandParams {
enum FieldId
{
    kEffectIdFieldId      = 0,
    kEffectVariantFieldId = 1,
};

struct Type
{
public:
    OnOffEffectIdentifier effectId;
    enum8 effectVariant;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OffWithEffectCommandParams
namespace OnCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OnCommandParams
namespace OnWithRecallGlobalSceneCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OnWithRecallGlobalSceneCommandParams
namespace OnWithTimedOffCommandParams {
enum FieldId
{
    kOnOffControlFieldId = 0,
    kOnTimeFieldId       = 1,
    kOffWaitTimeFieldId  = 2,
};

struct Type
{
public:
    uint8_t onOffControl;
    uint16_t onTime;
    uint16_t offWaitTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OnWithTimedOffCommandParams
namespace ToggleCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ToggleCommandParams

} // namespace OnOff

// OnOffSwitchConfiguration Cluster Commands
namespace OnOffSwitchConfiguration {

} // namespace OnOffSwitchConfiguration

// OperationalCredentials Cluster Commands
namespace OperationalCredentials {

namespace AddNOCCommandParams {
enum FieldId
{
    kNOCValueFieldId      = 0,
    kICACValueFieldId     = 1,
    kIPKValueFieldId      = 2,
    kCaseAdminNodeFieldId = 3,
    kAdminVendorIdFieldId = 4,
};

struct Type
{
public:
    chip::ByteSpan nOCValue;
    chip::ByteSpan iCACValue;
    chip::ByteSpan iPKValue;
    uint64_t caseAdminNode;
    uint16_t adminVendorId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddNOCCommandParams
namespace AddTrustedRootCertificateCommandParams {
enum FieldId
{
    kRootCertificateFieldId = 0,
};

struct Type
{
public:
    chip::ByteSpan rootCertificate;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddTrustedRootCertificateCommandParams
namespace AttestationRequestCommandParams {
enum FieldId
{
    kAttestationNonceFieldId = 0,
};

struct Type
{
public:
    chip::ByteSpan attestationNonce;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AttestationRequestCommandParams
namespace CertificateChainRequestCommandParams {
enum FieldId
{
    kCertificateTypeFieldId = 0,
};

struct Type
{
public:
    uint8_t certificateType;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CertificateChainRequestCommandParams
namespace OpCSRRequestCommandParams {
enum FieldId
{
    kCSRNonceFieldId = 0,
};

struct Type
{
public:
    chip::ByteSpan cSRNonce;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OpCSRRequestCommandParams
namespace RemoveFabricCommandParams {
enum FieldId
{
    kFabricIndexFieldId = 0,
};

struct Type
{
public:
    uint8_t fabricIndex;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveFabricCommandParams
namespace RemoveTrustedRootCertificateCommandParams {
enum FieldId
{
    kTrustedRootIdentifierFieldId = 0,
};

struct Type
{
public:
    chip::ByteSpan trustedRootIdentifier;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveTrustedRootCertificateCommandParams
namespace UpdateFabricLabelCommandParams {
enum FieldId
{
    kLabelFieldId = 0,
};

struct Type
{
public:
    Span<const char> label;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateFabricLabelCommandParams
namespace UpdateNOCCommandParams {
enum FieldId
{
    kNOCValueFieldId  = 0,
    kICACValueFieldId = 1,
};

struct Type
{
public:
    chip::ByteSpan nOCValue;
    chip::ByteSpan iCACValue;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateNOCCommandParams

namespace AttestationResponseCommandParams {
enum FieldId
{
    kAttestationElementsFieldId = 0,
    kSignatureFieldId           = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AttestationResponseCommandParams
namespace CertificateChainResponseCommandParams {
enum FieldId
{
    kCertificateFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CertificateChainResponseCommandParams
namespace NOCResponseCommandParams {
enum FieldId
{
    kStatusCodeFieldId  = 0,
    kFabricIndexFieldId = 1,
    kDebugTextFieldId   = 2,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace NOCResponseCommandParams
namespace OpCSRResponseCommandParams {
enum FieldId
{
    kNOCSRElementsFieldId        = 0,
    kAttestationSignatureFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OpCSRResponseCommandParams

} // namespace OperationalCredentials

// PowerSource Cluster Commands
namespace PowerSource {

} // namespace PowerSource

// PressureMeasurement Cluster Commands
namespace PressureMeasurement {

} // namespace PressureMeasurement

// PumpConfigurationAndControl Cluster Commands
namespace PumpConfigurationAndControl {

} // namespace PumpConfigurationAndControl

// RelativeHumidityMeasurement Cluster Commands
namespace RelativeHumidityMeasurement {

} // namespace RelativeHumidityMeasurement

// Scenes Cluster Commands
namespace Scenes {

namespace AddSceneCommandParams {
enum FieldId
{
    kGroupIdFieldId        = 0,
    kSceneIdFieldId        = 1,
    kTransitionTimeFieldId = 2,
    kSceneNameFieldId      = 3,
    kClusterIdFieldId      = 4,
    kLengthFieldId         = 5,
    kValueFieldId          = 6,
};

struct Type
{
public:
    uint16_t groupId;
    uint8_t sceneId;
    uint16_t transitionTime;
    Span<const char> sceneName;
    uint32_t clusterId;
    uint8_t length;
    uint8_t value;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddSceneCommandParams
namespace GetSceneMembershipCommandParams {
enum FieldId
{
    kGroupIdFieldId = 0,
};

struct Type
{
public:
    uint16_t groupId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetSceneMembershipCommandParams
namespace RecallSceneCommandParams {
enum FieldId
{
    kGroupIdFieldId        = 0,
    kSceneIdFieldId        = 1,
    kTransitionTimeFieldId = 2,
};

struct Type
{
public:
    uint16_t groupId;
    uint8_t sceneId;
    uint16_t transitionTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RecallSceneCommandParams
namespace RemoveAllScenesCommandParams {
enum FieldId
{
    kGroupIdFieldId = 0,
};

struct Type
{
public:
    uint16_t groupId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveAllScenesCommandParams
namespace RemoveSceneCommandParams {
enum FieldId
{
    kGroupIdFieldId = 0,
    kSceneIdFieldId = 1,
};

struct Type
{
public:
    uint16_t groupId;
    uint8_t sceneId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveSceneCommandParams
namespace StoreSceneCommandParams {
enum FieldId
{
    kGroupIdFieldId = 0,
    kSceneIdFieldId = 1,
};

struct Type
{
public:
    uint16_t groupId;
    uint8_t sceneId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StoreSceneCommandParams
namespace ViewSceneCommandParams {
enum FieldId
{
    kGroupIdFieldId = 0,
    kSceneIdFieldId = 1,
};

struct Type
{
public:
    uint16_t groupId;
    uint8_t sceneId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ViewSceneCommandParams

namespace AddSceneResponseCommandParams {
enum FieldId
{
    kStatusFieldId  = 0,
    kGroupIdFieldId = 1,
    kSceneIdFieldId = 2,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddSceneResponseCommandParams
namespace GetSceneMembershipResponseCommandParams {
enum FieldId
{
    kStatusFieldId     = 0,
    kCapacityFieldId   = 1,
    kGroupIdFieldId    = 2,
    kSceneCountFieldId = 3,
    kSceneListFieldId  = 4,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetSceneMembershipResponseCommandParams
namespace RemoveAllScenesResponseCommandParams {
enum FieldId
{
    kStatusFieldId  = 0,
    kGroupIdFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveAllScenesResponseCommandParams
namespace RemoveSceneResponseCommandParams {
enum FieldId
{
    kStatusFieldId  = 0,
    kGroupIdFieldId = 1,
    kSceneIdFieldId = 2,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveSceneResponseCommandParams
namespace StoreSceneResponseCommandParams {
enum FieldId
{
    kStatusFieldId  = 0,
    kGroupIdFieldId = 1,
    kSceneIdFieldId = 2,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StoreSceneResponseCommandParams
namespace ViewSceneResponseCommandParams {
enum FieldId
{
    kStatusFieldId             = 0,
    kGroupIdFieldId            = 1,
    kSceneIdFieldId            = 2,
    kTransitionTimeFieldId     = 3,
    kSceneNameFieldId          = 4,
    kExtensionFieldSetsFieldId = 5,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ViewSceneResponseCommandParams

} // namespace Scenes

// SoftwareDiagnostics Cluster Commands
namespace SoftwareDiagnostics {

namespace ResetWatermarksCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ResetWatermarksCommandParams

} // namespace SoftwareDiagnostics

// Switch Cluster Commands
namespace Switch {

} // namespace Switch

// TvChannel Cluster Commands
namespace TvChannel {

namespace ChangeChannelCommandParams {
enum FieldId
{
    kMatchFieldId = 0,
};

struct Type
{
public:
    Span<const char> match;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ChangeChannelCommandParams
namespace ChangeChannelByNumberCommandParams {
enum FieldId
{
    kMajorNumberFieldId = 0,
    kMinorNumberFieldId = 1,
};

struct Type
{
public:
    uint16_t majorNumber;
    uint16_t minorNumber;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ChangeChannelByNumberCommandParams
namespace SkipChannelCommandParams {
enum FieldId
{
    kCountFieldId = 0,
};

struct Type
{
public:
    uint16_t count;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SkipChannelCommandParams

namespace ChangeChannelResponseCommandParams {
enum FieldId
{
    kChannelMatchFieldId = 0,
    kErrorTypeFieldId    = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ChangeChannelResponseCommandParams

} // namespace TvChannel

// TargetNavigator Cluster Commands
namespace TargetNavigator {

namespace NavigateTargetCommandParams {
enum FieldId
{
    kTargetFieldId = 0,
    kDataFieldId   = 1,
};

struct Type
{
public:
    uint8_t target;
    Span<const char> data;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace NavigateTargetCommandParams

namespace NavigateTargetResponseCommandParams {
enum FieldId
{
    kStatusFieldId = 0,
    kDataFieldId   = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace NavigateTargetResponseCommandParams

} // namespace TargetNavigator

// TemperatureMeasurement Cluster Commands
namespace TemperatureMeasurement {

} // namespace TemperatureMeasurement

// TestCluster Cluster Commands
namespace TestCluster {

namespace TestCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace TestCommandParams
namespace TestAddArgumentsCommandParams {
enum FieldId
{
    kArg1FieldId = 0,
    kArg2FieldId = 1,
};

struct Type
{
public:
    uint8_t arg1;
    uint8_t arg2;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace TestAddArgumentsCommandParams
namespace TestNotHandledCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace TestNotHandledCommandParams
namespace TestSpecificCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace TestSpecificCommandParams
namespace TestUnknownCommandCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace TestUnknownCommandCommandParams

namespace TestAddArgumentsResponseCommandParams {
enum FieldId
{
    kReturnValueFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace TestAddArgumentsResponseCommandParams
namespace TestSpecificResponseCommandParams {
enum FieldId
{
    kReturnValueFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace TestSpecificResponseCommandParams

} // namespace TestCluster

// Thermostat Cluster Commands
namespace Thermostat {

namespace ClearWeeklyScheduleCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ClearWeeklyScheduleCommandParams
namespace GetRelayStatusLogCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetRelayStatusLogCommandParams
namespace GetWeeklyScheduleCommandParams {
enum FieldId
{
    kDaysToReturnFieldId = 0,
    kModeToReturnFieldId = 1,
};

struct Type
{
public:
    uint8_t daysToReturn;
    uint8_t modeToReturn;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetWeeklyScheduleCommandParams
namespace SetWeeklyScheduleCommandParams {
enum FieldId
{
    kNumberOfTransitionsForSequenceFieldId = 0,
    kDayOfWeekForSequenceFieldId           = 1,
    kModeForSequenceFieldId                = 2,
    kPayloadFieldId                        = 3,
};

struct Type
{
public:
    uint8_t numberOfTransitionsForSequence;
    uint8_t dayOfWeekForSequence;
    uint8_t modeForSequence;
    DataModel::List<uint8_t> payload;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetWeeklyScheduleCommandParams
namespace SetpointRaiseLowerCommandParams {
enum FieldId
{
    kModeFieldId   = 0,
    kAmountFieldId = 1,
};

struct Type
{
public:
    SetpointAdjustMode mode;
    int8_t amount;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetpointRaiseLowerCommandParams

} // namespace Thermostat

// ThermostatUserInterfaceConfiguration Cluster Commands
namespace ThermostatUserInterfaceConfiguration {

} // namespace ThermostatUserInterfaceConfiguration

// ThreadNetworkDiagnostics Cluster Commands
namespace ThreadNetworkDiagnostics {

namespace ResetCountsCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ResetCountsCommandParams

} // namespace ThreadNetworkDiagnostics

// WakeOnLan Cluster Commands
namespace WakeOnLan {

} // namespace WakeOnLan

// WiFiNetworkDiagnostics Cluster Commands
namespace WiFiNetworkDiagnostics {

namespace ResetCountsCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ResetCountsCommandParams

} // namespace WiFiNetworkDiagnostics

// WindowCovering Cluster Commands
namespace WindowCovering {

namespace DownOrCloseCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace DownOrCloseCommandParams
namespace GoToLiftPercentageCommandParams {
enum FieldId
{
    kLiftPercentageValueFieldId    = 0,
    kLiftPercent100thsValueFieldId = 1,
};

struct Type
{
public:
    uint8_t liftPercentageValue;
    uint16_t liftPercent100thsValue;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GoToLiftPercentageCommandParams
namespace GoToLiftValueCommandParams {
enum FieldId
{
    kLiftValueFieldId = 0,
};

struct Type
{
public:
    uint16_t liftValue;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GoToLiftValueCommandParams
namespace GoToTiltPercentageCommandParams {
enum FieldId
{
    kTiltPercentageValueFieldId    = 0,
    kTiltPercent100thsValueFieldId = 1,
};

struct Type
{
public:
    uint8_t tiltPercentageValue;
    uint16_t tiltPercent100thsValue;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GoToTiltPercentageCommandParams
namespace GoToTiltValueCommandParams {
enum FieldId
{
    kTiltValueFieldId = 0,
};

struct Type
{
public:
    uint16_t tiltValue;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GoToTiltValueCommandParams
namespace StopMotionCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StopMotionCommandParams
namespace UpOrOpenCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpOrOpenCommandParams

} // namespace WindowCovering

} // namespace clusters
} // namespace app
} // namespace chip
