/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include "cluster_objects_commands.h"

#include <app-common/zap-generated/cluster-objects.h>

#pragma GCC diagnostic ignored "-Wstack-usage="

namespace chip {
namespace app {
namespace clusters {

namespace OtaSoftwareUpdateProvider {
namespace ApplyUpdateRequestCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kUpdateTokenFieldId), updateToken));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kNewVersionFieldId), newVersion));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace ApplyUpdateRequestCommandParams
namespace NotifyUpdateAppliedCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kUpdateTokenFieldId), updateToken));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kCurrentVersionFieldId), currentVersion));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace NotifyUpdateAppliedCommandParams
namespace QueryImageCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kVendorIdFieldId), vendorId));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kProductIdFieldId), productId));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kImageTypeFieldId), imageType));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kHardwareVersionFieldId), hardwareVersion));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kCurrentVersionFieldId), currentVersion));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kProtocolsSupportedFieldId), protocolsSupported));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kLocationFieldId), location));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kRequestorCanConsentFieldId), requestorCanConsent));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kMetadataForProviderFieldId), metadataForProvider));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace QueryImageCommandParams

namespace ApplyUpdateRequestResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace ApplyUpdateRequestResponseCommandParams
namespace QueryImageResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace QueryImageResponseCommandParams

} // namespace OtaSoftwareUpdateProvider

} // namespace clusters
} // namespace app
} // namespace chip
