/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app-common/zap-generated/cluster-objects.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/Decode.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/util/basic-types.h>

namespace chip {
namespace app {
namespace clusters {

// OtaSoftwareUpdateProvider Cluster Commands
namespace OtaSoftwareUpdateProvider {

namespace ApplyUpdateRequestCommandParams {
enum FieldId
{
    kUpdateTokenFieldId = 0,
    kNewVersionFieldId  = 1,
};

struct Type
{
public:
    chip::ByteSpan updateToken;
    uint32_t newVersion;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ApplyUpdateRequestCommandParams
namespace NotifyUpdateAppliedCommandParams {
enum FieldId
{
    kUpdateTokenFieldId    = 0,
    kCurrentVersionFieldId = 1,
};

struct Type
{
public:
    chip::ByteSpan updateToken;
    uint32_t currentVersion;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace NotifyUpdateAppliedCommandParams
namespace QueryImageCommandParams {
enum FieldId
{
    kVendorIdFieldId            = 0,
    kProductIdFieldId           = 1,
    kImageTypeFieldId           = 2,
    kHardwareVersionFieldId     = 3,
    kCurrentVersionFieldId      = 4,
    kProtocolsSupportedFieldId  = 5,
    kLocationFieldId            = 6,
    kRequestorCanConsentFieldId = 7,
    kMetadataForProviderFieldId = 8,
};

struct Type
{
public:
    uint16_t vendorId;
    uint16_t productId;
    uint16_t imageType;
    uint16_t hardwareVersion;
    uint32_t currentVersion;
    OTADownloadProtocol protocolsSupported;
    Span<const char> location;
    bool requestorCanConsent;
    chip::ByteSpan metadataForProvider;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace QueryImageCommandParams

namespace ApplyUpdateRequestResponseCommandParams {
enum FieldId
{
    kActionFieldId            = 0,
    kDelayedActionTimeFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ApplyUpdateRequestResponseCommandParams
namespace QueryImageResponseCommandParams {
enum FieldId
{
    kStatusFieldId               = 0,
    kDelayedActionTimeFieldId    = 1,
    kImageURIFieldId             = 2,
    kSoftwareVersionFieldId      = 3,
    kUpdateTokenFieldId          = 4,
    kUserConsentNeededFieldId    = 5,
    kMetadataForRequestorFieldId = 6,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace QueryImageResponseCommandParams

} // namespace OtaSoftwareUpdateProvider

} // namespace clusters
} // namespace app
} // namespace chip
