/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include "cluster_objects_commands.h"

#include <app-common/zap-generated/cluster-objects.h>

#pragma GCC diagnostic ignored "-Wstack-usage="

namespace chip {
namespace app {
namespace clusters {

namespace GeneralCommissioning {
namespace ArmFailSafeCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kExpiryLengthSecondsFieldId), expiryLengthSeconds));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kBreadcrumbFieldId), breadcrumb));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTimeoutMsFieldId), timeoutMs));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace ArmFailSafeCommandParams
namespace CommissioningCompleteCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace CommissioningCompleteCommandParams
namespace SetRegulatoryConfigCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kLocationFieldId), location));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kCountryCodeFieldId), countryCode));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kBreadcrumbFieldId), breadcrumb));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTimeoutMsFieldId), timeoutMs));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace SetRegulatoryConfigCommandParams

namespace ArmFailSafeResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace ArmFailSafeResponseCommandParams
namespace CommissioningCompleteResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace CommissioningCompleteResponseCommandParams
namespace SetRegulatoryConfigResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace SetRegulatoryConfigResponseCommandParams

} // namespace GeneralCommissioning
namespace NetworkCommissioning {
namespace DisableNetworkCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kNetworkIDFieldId), networkID));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kBreadcrumbFieldId), breadcrumb));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTimeoutMsFieldId), timeoutMs));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace DisableNetworkCommandParams
namespace EnableNetworkCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kNetworkIDFieldId), networkID));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kBreadcrumbFieldId), breadcrumb));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTimeoutMsFieldId), timeoutMs));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace EnableNetworkCommandParams
namespace GetLastNetworkCommissioningResultCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTimeoutMsFieldId), timeoutMs));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace GetLastNetworkCommissioningResultCommandParams
namespace RemoveNetworkCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kNetworkIDFieldId), networkID));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kBreadcrumbFieldId), breadcrumb));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTimeoutMsFieldId), timeoutMs));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace RemoveNetworkCommandParams
namespace ScanNetworksCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kSsidFieldId), ssid));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kBreadcrumbFieldId), breadcrumb));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTimeoutMsFieldId), timeoutMs));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace ScanNetworksCommandParams

namespace AddThreadNetworkResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace AddThreadNetworkResponseCommandParams
namespace AddWiFiNetworkResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace AddWiFiNetworkResponseCommandParams
namespace DisableNetworkResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace DisableNetworkResponseCommandParams
namespace EnableNetworkResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace EnableNetworkResponseCommandParams
namespace RemoveNetworkResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace RemoveNetworkResponseCommandParams
namespace ScanNetworksResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace ScanNetworksResponseCommandParams
namespace UpdateThreadNetworkResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace UpdateThreadNetworkResponseCommandParams
namespace UpdateWiFiNetworkResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace UpdateWiFiNetworkResponseCommandParams

} // namespace NetworkCommissioning
namespace OperationalCredentials {
namespace AddNOCCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kNOCValueFieldId), nOCValue));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kICACValueFieldId), iCACValue));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kIPKValueFieldId), iPKValue));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kCaseAdminNodeFieldId), caseAdminNode));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kAdminVendorIdFieldId), adminVendorId));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace AddNOCCommandParams
namespace AddTrustedRootCertificateCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kRootCertificateFieldId), rootCertificate));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace AddTrustedRootCertificateCommandParams
namespace AttestationRequestCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kAttestationNonceFieldId), attestationNonce));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace AttestationRequestCommandParams
namespace CertificateChainRequestCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kCertificateTypeFieldId), certificateType));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace CertificateChainRequestCommandParams
namespace OpCSRRequestCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kCSRNonceFieldId), cSRNonce));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace OpCSRRequestCommandParams
namespace RemoveFabricCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kFabricIndexFieldId), fabricIndex));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace RemoveFabricCommandParams
namespace UpdateFabricLabelCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kLabelFieldId), label));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace UpdateFabricLabelCommandParams

namespace AttestationResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace AttestationResponseCommandParams
namespace CertificateChainResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace CertificateChainResponseCommandParams
namespace NOCResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace NOCResponseCommandParams
namespace OpCSRResponseCommandParams {
CHIP_ERROR Type::Decode(TLV::TLVReader & reader)
{
    return CHIP_ERROR_NOT_IMPLEMENTED;
}
} // namespace OpCSRResponseCommandParams

} // namespace OperationalCredentials

} // namespace clusters
} // namespace app
} // namespace chip
