/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app-common/zap-generated/cluster-objects.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/Decode.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/util/basic-types.h>

namespace chip {
namespace app {
namespace clusters {

// GeneralCommissioning Cluster Commands
namespace GeneralCommissioning {

namespace ArmFailSafeCommandParams {
enum FieldId
{
    kExpiryLengthSecondsFieldId = 0,
    kBreadcrumbFieldId          = 1,
    kTimeoutMsFieldId           = 2,
};

struct Type
{
public:
    uint16_t expiryLengthSeconds;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ArmFailSafeCommandParams
namespace CommissioningCompleteCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CommissioningCompleteCommandParams
namespace SetRegulatoryConfigCommandParams {
enum FieldId
{
    kLocationFieldId    = 0,
    kCountryCodeFieldId = 1,
    kBreadcrumbFieldId  = 2,
    kTimeoutMsFieldId   = 3,
};

struct Type
{
public:
    RegulatoryLocationType location;
    Span<const char> countryCode;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetRegulatoryConfigCommandParams

namespace ArmFailSafeResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ArmFailSafeResponseCommandParams
namespace CommissioningCompleteResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CommissioningCompleteResponseCommandParams
namespace SetRegulatoryConfigResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace SetRegulatoryConfigResponseCommandParams

} // namespace GeneralCommissioning

// NetworkCommissioning Cluster Commands
namespace NetworkCommissioning {

namespace DisableNetworkCommandParams {
enum FieldId
{
    kNetworkIDFieldId  = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan networkID;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace DisableNetworkCommandParams
namespace EnableNetworkCommandParams {
enum FieldId
{
    kNetworkIDFieldId  = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan networkID;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnableNetworkCommandParams
namespace GetLastNetworkCommissioningResultCommandParams {
enum FieldId
{
    kTimeoutMsFieldId = 0,
};

struct Type
{
public:
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace GetLastNetworkCommissioningResultCommandParams
namespace RemoveNetworkCommandParams {
enum FieldId
{
    kNetworkIDFieldId  = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan networkID;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveNetworkCommandParams
namespace ScanNetworksCommandParams {
enum FieldId
{
    kSsidFieldId       = 0,
    kBreadcrumbFieldId = 1,
    kTimeoutMsFieldId  = 2,
};

struct Type
{
public:
    chip::ByteSpan ssid;
    uint64_t breadcrumb;
    uint32_t timeoutMs;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ScanNetworksCommandParams

namespace AddThreadNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddThreadNetworkResponseCommandParams
namespace AddWiFiNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddWiFiNetworkResponseCommandParams
namespace DisableNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace DisableNetworkResponseCommandParams
namespace EnableNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace EnableNetworkResponseCommandParams
namespace RemoveNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveNetworkResponseCommandParams
namespace ScanNetworksResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId         = 0,
    kDebugTextFieldId         = 1,
    kWifiScanResultsFieldId   = 2,
    kThreadScanResultsFieldId = 3,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ScanNetworksResponseCommandParams
namespace UpdateThreadNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateThreadNetworkResponseCommandParams
namespace UpdateWiFiNetworkResponseCommandParams {
enum FieldId
{
    kErrorCodeFieldId = 0,
    kDebugTextFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateWiFiNetworkResponseCommandParams

} // namespace NetworkCommissioning

// OperationalCredentials Cluster Commands
namespace OperationalCredentials {

namespace AddNOCCommandParams {
enum FieldId
{
    kNOCValueFieldId      = 0,
    kICACValueFieldId     = 1,
    kIPKValueFieldId      = 2,
    kCaseAdminNodeFieldId = 3,
    kAdminVendorIdFieldId = 4,
};

struct Type
{
public:
    chip::ByteSpan nOCValue;
    chip::ByteSpan iCACValue;
    chip::ByteSpan iPKValue;
    uint64_t caseAdminNode;
    uint16_t adminVendorId;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddNOCCommandParams
namespace AddTrustedRootCertificateCommandParams {
enum FieldId
{
    kRootCertificateFieldId = 0,
};

struct Type
{
public:
    chip::ByteSpan rootCertificate;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AddTrustedRootCertificateCommandParams
namespace AttestationRequestCommandParams {
enum FieldId
{
    kAttestationNonceFieldId = 0,
};

struct Type
{
public:
    chip::ByteSpan attestationNonce;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AttestationRequestCommandParams
namespace CertificateChainRequestCommandParams {
enum FieldId
{
    kCertificateTypeFieldId = 0,
};

struct Type
{
public:
    uint8_t certificateType;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CertificateChainRequestCommandParams
namespace OpCSRRequestCommandParams {
enum FieldId
{
    kCSRNonceFieldId = 0,
};

struct Type
{
public:
    chip::ByteSpan cSRNonce;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OpCSRRequestCommandParams
namespace RemoveFabricCommandParams {
enum FieldId
{
    kFabricIndexFieldId = 0,
};

struct Type
{
public:
    uint8_t fabricIndex;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace RemoveFabricCommandParams
namespace UpdateFabricLabelCommandParams {
enum FieldId
{
    kLabelFieldId = 0,
};

struct Type
{
public:
    Span<const char> label;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace UpdateFabricLabelCommandParams

namespace AttestationResponseCommandParams {
enum FieldId
{
    kAttestationElementsFieldId = 0,
    kSignatureFieldId           = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace AttestationResponseCommandParams
namespace CertificateChainResponseCommandParams {
enum FieldId
{
    kCertificateFieldId = 0,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace CertificateChainResponseCommandParams
namespace NOCResponseCommandParams {
enum FieldId
{
    kStatusCodeFieldId  = 0,
    kFabricIndexFieldId = 1,
    kDebugTextFieldId   = 2,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace NOCResponseCommandParams
namespace OpCSRResponseCommandParams {
enum FieldId
{
    kNOCSRElementsFieldId        = 0,
    kAttestationSignatureFieldId = 1,
};

struct Type
{
public:
    // TODO

    CHIP_ERROR Decode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OpCSRResponseCommandParams

} // namespace OperationalCredentials

} // namespace clusters
} // namespace app
} // namespace chip
