/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include "cluster_objects_commands.h"

#include <app-common/zap-generated/cluster-objects.h>

#pragma GCC diagnostic ignored "-Wstack-usage="

namespace chip {
namespace app {
namespace clusters {

namespace FlowMeasurement {

}
namespace LevelControl {
namespace MoveCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kMoveModeFieldId), moveMode));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kRateFieldId), rate));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionMaskFieldId), optionMask));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionOverrideFieldId), optionOverride));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace MoveCommandParams
namespace MoveToLevelCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kLevelFieldId), level));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTransitionTimeFieldId), transitionTime));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionMaskFieldId), optionMask));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionOverrideFieldId), optionOverride));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace MoveToLevelCommandParams
namespace MoveToLevelWithOnOffCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kLevelFieldId), level));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTransitionTimeFieldId), transitionTime));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace MoveToLevelWithOnOffCommandParams
namespace MoveWithOnOffCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kMoveModeFieldId), moveMode));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kRateFieldId), rate));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace MoveWithOnOffCommandParams
namespace StepCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kStepModeFieldId), stepMode));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kStepSizeFieldId), stepSize));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTransitionTimeFieldId), transitionTime));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionMaskFieldId), optionMask));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionOverrideFieldId), optionOverride));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace StepCommandParams
namespace StepWithOnOffCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kStepModeFieldId), stepMode));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kStepSizeFieldId), stepSize));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kTransitionTimeFieldId), transitionTime));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace StepWithOnOffCommandParams
namespace StopCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionMaskFieldId), optionMask));
    ReturnErrorOnFailure(DataModel::Encode(writer, TLV::ContextTag(kOptionOverrideFieldId), optionOverride));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace StopCommandParams
namespace StopWithOnOffCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace StopWithOnOffCommandParams

} // namespace LevelControl
namespace OnOff {
namespace OffCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace OffCommandParams
namespace OnCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace OnCommandParams
namespace ToggleCommandParams {

CHIP_ERROR Type::Encode(TLV::TLVWriter & writer, uint64_t tag) const
{
    TLV::TLVType outer;
    ReturnErrorOnFailure(writer.StartContainer(tag, TLV::kTLVType_Structure, outer));
    ReturnErrorOnFailure(writer.EndContainer(outer));
    return CHIP_NO_ERROR;
}

} // namespace ToggleCommandParams

} // namespace OnOff
namespace PressureMeasurement {

}
namespace PumpConfigurationAndControl {

}
namespace TemperatureMeasurement {

}

} // namespace clusters
} // namespace app
} // namespace chip
