/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app-common/zap-generated/cluster-objects.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/Decode.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/util/basic-types.h>

namespace chip {
namespace app {
namespace clusters {

// FlowMeasurement Cluster Commands
namespace FlowMeasurement {

} // namespace FlowMeasurement

// LevelControl Cluster Commands
namespace LevelControl {

namespace MoveCommandParams {
enum FieldId
{
    kMoveModeFieldId       = 0,
    kRateFieldId           = 1,
    kOptionMaskFieldId     = 2,
    kOptionOverrideFieldId = 3,
};

struct Type
{
public:
    MoveMode moveMode;
    uint8_t rate;
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveCommandParams
namespace MoveToLevelCommandParams {
enum FieldId
{
    kLevelFieldId          = 0,
    kTransitionTimeFieldId = 1,
    kOptionMaskFieldId     = 2,
    kOptionOverrideFieldId = 3,
};

struct Type
{
public:
    uint8_t level;
    uint16_t transitionTime;
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToLevelCommandParams
namespace MoveToLevelWithOnOffCommandParams {
enum FieldId
{
    kLevelFieldId          = 0,
    kTransitionTimeFieldId = 1,
};

struct Type
{
public:
    uint8_t level;
    uint16_t transitionTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveToLevelWithOnOffCommandParams
namespace MoveWithOnOffCommandParams {
enum FieldId
{
    kMoveModeFieldId = 0,
    kRateFieldId     = 1,
};

struct Type
{
public:
    MoveMode moveMode;
    uint8_t rate;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace MoveWithOnOffCommandParams
namespace StepCommandParams {
enum FieldId
{
    kStepModeFieldId       = 0,
    kStepSizeFieldId       = 1,
    kTransitionTimeFieldId = 2,
    kOptionMaskFieldId     = 3,
    kOptionOverrideFieldId = 4,
};

struct Type
{
public:
    StepMode stepMode;
    uint8_t stepSize;
    uint16_t transitionTime;
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepCommandParams
namespace StepWithOnOffCommandParams {
enum FieldId
{
    kStepModeFieldId       = 0,
    kStepSizeFieldId       = 1,
    kTransitionTimeFieldId = 2,
};

struct Type
{
public:
    StepMode stepMode;
    uint8_t stepSize;
    uint16_t transitionTime;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StepWithOnOffCommandParams
namespace StopCommandParams {
enum FieldId
{
    kOptionMaskFieldId     = 0,
    kOptionOverrideFieldId = 1,
};

struct Type
{
public:
    uint8_t optionMask;
    uint8_t optionOverride;

    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StopCommandParams
namespace StopWithOnOffCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace StopWithOnOffCommandParams

} // namespace LevelControl

// OnOff Cluster Commands
namespace OnOff {

namespace OffCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OffCommandParams
namespace OnCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace OnCommandParams
namespace ToggleCommandParams {
enum FieldId
{
};

struct Type
{
public:
    CHIP_ERROR Encode(TLV::TLVWriter & writer, uint64_t tag) const;
};
} // namespace ToggleCommandParams

} // namespace OnOff

// PressureMeasurement Cluster Commands
namespace PressureMeasurement {

} // namespace PressureMeasurement

// PumpConfigurationAndControl Cluster Commands
namespace PumpConfigurationAndControl {

} // namespace PumpConfigurationAndControl

// TemperatureMeasurement Cluster Commands
namespace TemperatureMeasurement {

} // namespace TemperatureMeasurement

} // namespace clusters
} // namespace app
} // namespace chip
